export const STARTLISTTASK = 'STARTLISTTASK';
export const SUCCESSLISTTASK = 'SUCCESSLISTTASK';
export const FAILLISTTASK = 'FAILLISTTASK';


export const STARTCREATETASK = 'STARTCREATETASK'
export const SUCCESSCREATETASK = 'SUCCESSCREATETASK'
export const FAILCREATETASK = 'FAILCREATETASK'



export const STARTDELETETASK = 'STARTDELETETASK'
export const SUCCESSDELETETASK = 'SUCCESSDELETETASK'
export const FAILDELETETASK = 'FAILDELETETASK'



export const STARTUPDATETASK = 'STARTUPDATETASK'
export const SUCCESSUPDATETASK = 'SUCCESSUPDATETASK'
export const FAILUPDATETASK = 'FAILUPDATETASK'


export const STARTLOGINUSER = 'STARTLOGINUSER'
export const SUCCESSLOGINUSER = 'SUCCESSLOGINUSER'
export const FAILLOGINUSER = 'FAILLOGINUSER'

export const STARTSIGNUPUSER = 'STARTSIGNUPUSER'
export const SUCCESSIGNUPUSER = 'SUCESSIGNUPUSER'
export const FAILSIGNUPUSER = 'FAILSIGNUPUSER'